name: CI World News
on:
  push:
    branches: [main, preprod]
  pull_request:
    branches: [main, preprod]
jobs:
  quality-check:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install all dependencies
        run: |
          npm install
          npm install --prefix wn-falcon-reader/server
          npm install --prefix wn-falcon-reader/client
          npm install --prefix wn-falcon-writer/server
          npm install --prefix wn-falcon-writer/client

      - name: Initialize Database Schema
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: psql -h localhost -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -f ./init-db/2_init_db.sql

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Linter
        run: npm run lint:all

      - name: Run unit & integration tests (Vitest)
        env:
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          READER_BACK_PORT: ${{ vars.READER_BACK_PORT }}
          WRITER_BACK_PORT: ${{ vars.WRITER_BACK_PORT }}
        run: npm run ci:test

      - name: Run E2E tests (Playwright)
        env:
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          READER_BACK_PORT: ${{ vars.READER_BACK_PORT }}
          WRITER_BACK_PORT: ${{ vars.WRITER_BACK_PORT }}
          READER_FRONT_PORT: ${{ vars.READER_FRONT_PORT }}
          WRITER_FRONT_PORT: ${{ vars.WRITER_FRONT_PORT }}
        run: npx playwright test
